// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCV3BC-DngJwLrF9qvypT5us9zE28nt44',
    appId: '1:763717745226:web:0964008beaeb2307e104b3',
    messagingSenderId: '763717745226',
    projectId: 'flutter-application-62cb8',
    authDomain: 'flutter-application-62cb8.firebaseapp.com',
    storageBucket: 'flutter-application-62cb8.appspot.com',
    measurementId: 'G-LQFV3MZYCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszOvEVh0gyBSbQextf7oWO0bS9yHPqGY',
    appId: '1:763717745226:android:854df65723f25344e104b3',
    messagingSenderId: '763717745226',
    projectId: 'flutter-application-62cb8',
    storageBucket: 'flutter-application-62cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMA05var869MZdkHIIbYKDAsm7jc-XAkM',
    appId: '1:763717745226:ios:4200c32210f43150e104b3',
    messagingSenderId: '763717745226',
    projectId: 'flutter-application-62cb8',
    storageBucket: 'flutter-application-62cb8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMA05var869MZdkHIIbYKDAsm7jc-XAkM',
    appId: '1:763717745226:ios:f9d6d106ebfb9aa4e104b3',
    messagingSenderId: '763717745226',
    projectId: 'flutter-application-62cb8',
    storageBucket: 'flutter-application-62cb8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
